name: BkrTorchLight
main: ykt.BeYkeRYkt.BkrTorchLight.Recode.BTL
version: 3.0Recode
description: >
             Portable Torch + Server - side!
author: BeYkeRYkt
permissions:
    BTL.light:
        description: Light Permission
        default: true